name: tsf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - statsmodels
  - pmdarima
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3