name: tsf
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - requests
  - numpy
  - pandas
  - matplotlib
  - statsmodels
  - pmdarima
  - scikit-learn
  - xgboost
  - gcc
  - prophet